syntax = "proto3";

package power_msg;
import "std.proto";

message PowerStateStamped {
    std_msg.Header header = 1;
    bool pb1_digital = 2;
    bool pb1_signal = 3;
    bool pb1_power = 4;
    bool pb2_digital = 5;
    bool pb2_signal = 6;
    bool pb2_power = 7;
    bool clean = 8;
    double pb1_v_0  = 9;
    double pb1_i_0  = 10;
    double pb1_v_1  = 11;
    double pb1_i_1  = 12;
    double pb1_v_2  = 13;
    double pb1_i_2  = 14;
    double pb1_v_3  = 15;
    double pb1_i_3  = 16;
    double pb1_v_4  = 17;
    double pb1_i_4  = 18;
    double pb1_v_5  = 19;
    double pb1_i_5  = 20;
    double pb1_v_6  = 21;
    double pb1_i_6  = 22;
    double pb1_v_7  = 23;
    double pb1_i_7  = 24;
    double pb2_v_0  = 25;
    double pb2_i_0  = 26;
    double pb2_v_1  = 27;
    double pb2_i_1  = 28;
    double pb2_v_2  = 29;
    double pb2_i_2  = 30;
    double pb2_v_3  = 31;
    double pb2_i_3  = 32;
    double pb2_v_4  = 33;
    double pb2_i_4  = 34;
    double pb2_v_5  = 35;
    double pb2_i_5  = 36;
    double pb2_v_6  = 37;
    double pb2_i_6  = 38;
    double pb2_v_7  = 39;
    double pb2_i_7  = 40;
}